In [44]:
import numpy as np

In [45]:
#create array
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([[4,15,5],[87,9,95]])
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[[ 4 15  5]
 [87  9 95]]


In [46]:
vnew=np.vsplit(b,2)
print(vnew)

[array([[ 4, 15,  5]]), array([[87,  9, 95]])]


In [47]:
#return shape of a array
print(format(a.shape))
print(format(b.shape))

(9,)
(2, 3)


In [48]:
#return dimension of array 
print(a.ndim)
print(b.ndim)

1
2


In [49]:
#return size of array
print(format(a.size))

9


In [50]:
#return data type of array
print(a.dtype)

int64


In [51]:
#return item size of array
print(a.itemsize)

8


In [52]:
#return data of mamaory location array
print(a.data)

In [53]:
#return slice of array
slicearra=a[4:7]
slicearrb=b[1:,2:]
print(slicearra)
print(slicearrb)

[5 6 7]
[[95]]


In [54]:
#return sum of array
print(a.sum())
print(b.sum())

45
215


In [55]:
#opration of matrix create a new array 
m1=np.array([[1,2],[3,4]])
m2=np.array([[6,7],[8,9]])
print(m1)
print(m2)

# cross multiply of matrix  
mul = np.dot(m1,m2)
print(mul)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[22 25]
 [50 57]]


In [56]:
# row column multipication
mulM=np.multiply(m1,m2)
print(mulM)

[[ 6 14]
 [24 36]]


In [57]:
#add of matrix
addM= np.add(m1,m2)
print(addM)

[[ 7  9]
 [11 13]]


In [58]:
#sub of matrix
subM= np.subtract(m1,m2)
print(subM)

[[-5 -5]
 [-5 -5]]


In [59]:
#convert array to matrex
M3=np.array([1,2,3,4,5,6,7,8,9])
m3=M3.reshape(3,3)
print(m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
# find minimum value of matrix
print(m3.min())

1


In [61]:
# find maximum value of matrix
print(m3.max())

9


In [62]:
# find minimum value of each row 
print(m3.min(axis=1))


[1 4 7]


In [63]:
# find minimum value of each column 
print(m3.min(axis=0))


[1 2 3]


In [64]:
# find maxmum value of each row 
print(m3.max(axis=1))


[3 6 9]


In [65]:
# find maxmum value of each column 
print(m3.max(axis=0))


[7 8 9]


In [66]:
m4=np.array([[121,4,9],[16,49,81]])

# find a squre root of matrix
print(np.sqrt(m4))

[[11.  2.  3.]
 [ 4.  7.  9.]]


In [67]:
#print standard deviation ofn matrix 
print(np.std(a))

2.581988897471611


In [68]:
#create vertical stack
v=np.vstack((m1,m2))
print(v)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [69]:
#create vertical stack
h=np.hstack((m1,m2))
print(h)

[[1 2 6 7]
 [3 4 8 9]]


In [70]:
# provide a range between the number
rang=np.arange(0,20,2)
print(rang)

[ 0  2  4  6  8 10 12 14 16 18]


In [71]:
# provide a range between the number
rang=np.arange(0,20,2,float)
print(rang,rang.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.] float64


In [72]:
# divide number of this range in given part
divide=np.linspace(0,50,5)
print(divide)


[ 0.  12.5 25.  37.5 50. ]


In [73]:
#convert horizontal to vertical
ht=h.T
print(ht)

[[1 3]
 [2 4]
 [6 8]
 [7 9]]


In [74]:
#convert vertical to horizontal
vt=v.T
print(vt)


[[1 3 6 8]
 [2 4 7 9]]


In [75]:
# print each element of array
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9


In [89]:
ab=np.array([[4,5,2],[17,8,9],[6,54,52],[47,95,10]])

#split the array horizontal
h_split=np.hsplit(ab,3)
print(h_split)

#split the array vertically
v_split=np.vsplit(ab,2)
print(v_split)

[array([[ 4],
       [17],
       [ 6],
       [47]]), array([[ 5],
       [ 8],
       [54],
       [95]]), array([[ 2],
       [ 9],
       [52],
       [10]])]
[array([[ 4,  5,  2],
       [17,  8,  9]]), array([[ 6, 54, 52],
       [47, 95, 10]])]


In [91]:
abc=np.array([54,89,32,54])
#return the square root of each element
print(np.sqrt(abc))

#return the exponentials of each element
print(np.exp(abc))

#return the sin of each element
print(np.sin(abc))

#return the cos of each element
print(np.cos(abc))

#return the log of each element
print(np.log(abc))

#return the sum of total element of array
print(np.sum(abc))

#return the standard deviation of in the array
print(np.std(abc))

[7.34846923 9.43398113 5.65685425 7.34846923]
[2.83075330e+23 4.48961282e+38 7.89629602e+13 2.83075330e+23]
[-0.55878905  0.86006941  0.55142668 -0.55878905]
[-0.82930983  0.51017704  0.83422336 -0.82930983]
[3.98898405 4.48863637 3.4657359  3.98898405]
229
20.41292482717751


In [104]:
# random number genrator in floats
anw=np.random.random(5);
print(anw)

[0.31007285 0.29452194 0.06989604 0.39552828 0.68638012]


In [105]:
# random number genrator in given range
ran=np.random.rand(3,4)
print(ran)


[[0.14389071 0.98923476 0.82339383 0.51859406]
 [0.90050045 0.56069906 0.23707381 0.31702007]
 [0.13445463 0.9051147  0.86784302 0.49052162]]


In [106]:
# random in integer by range 
inte=np.random.randint(0,50,5)
print(inte)

[41 48 44 41 17]


In [108]:
# random permutation of number
per= np.random.permutation(np.arange(5))
print(per)

[3 1 2 0 4]
